name: build
on: [ push, pull_request ]
permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    name: cargo build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --verbose
